### ISSUE TITLE
tsc broken on dev: markdown-field.tsx references deleted ui/tooltip

### ISSUE THREAD

**Issue by cielbellerose** [SGAOperations/aplio#510]
`dev`'s tip (after merging #504 "remove dead code and unused dependencies") fails `npm run tsc:check`:

```
components/features/markdown-field.tsx(46,8): error TS2307: Cannot find module '@/components/ui/tooltip' or its corresponding type declarations.
```

Root cause: #390 (merged as `4f93125`, PR #504) deleted `components/ui/tooltip.tsx` and the `@radix-ui/react-tooltip` dependency as "unreferenced," based on a branch cut before #382 ("support markdown in position descriptions", merged as `7cbd35b`) landed. #382 added a `Tooltip`/`TooltipTrigger`/`TooltipContent` usage in `components/features/markdown-field.tsx`. Both PRs individually passed CI (#390's branch predated #382's tooltip usage), but merged back-to-back into `dev` roughly 4 minutes apart, so the combined tree on `dev` now references a component and dependency that no longer exist.

**Fix:** restore `components/ui/tooltip.tsx` (available at `git show 4f93125^:components/ui/tooltip.tsx`) and reinstall `@radix-ui/react-tooltip` (`npm install @radix-ui/react-tooltip`), or remove the tooltip usage from `markdown-field.tsx` if it's no longer wanted.

**Impact:** every PR that rebases onto current `dev` will see a red `tsc` check unrelated to its own changes.

Discovered while rebasing PR #497 onto `dev` (unrelated auth deactivation feature) — filing separately rather than fixing inline there.

---

## Overview

**Restore the primitive, keep the tooltips.** The markdown toolbar's icon-only buttons rely on tooltips to expose their label and keyboard shortcut (`Bold (Ctrl+B)`); that affordance shipped deliberately in #382 and #504 deleted its dependency on a stale premise, so the fix is to put the primitive and the package back — not to strip a reviewed feature to satisfy a bad deletion.

Re-add `@radix-ui/react-tooltip@^1.2.10` (the exact range #504 removed) and recreate `components/ui/tooltip.tsx` with the four exports `markdown-field.tsx` imports. Recreate it from `4f93125^` but bring it to the repo's **current** shadcn conventions — `data-slot` attributes and the live `tw-animate-css` animation set, as in `components/ui/dropdown-menu.tsx`. Keep the old file's surface tokens; only its four `animate-slideDownAndFade`/`slideUpAndFade`/`slideLeftAndFade`/`slideRightAndFade` classes must go: no such keyframes or `--animate-*` theme vars exist anywhere in the tree, before or after #504, so a verbatim restore would re-import dead classes and a tooltip that visibly doesn't animate.

No other reference from #504's deletions dangles — a tree-wide grep of `origin/dev` for `ui/calendar`, `ui/command`, `ui/popover`, `providers/query-provider`, `position-applications-table`, `getPositionApplications`, `getManagedPositionIds`, `getPositionAccess`, and `PositionApplicationListItem` finds nothing. `markdown-field.tsx:46` is the only breakage; this ticket is exactly that one import.

## Changes

- `components/ui/tooltip.tsx` — **create**: `Tooltip`, `TooltipTrigger`, `TooltipContent`, `TooltipProvider` wrappers over `@radix-ui/react-tooltip`; the module `markdown-field.tsx` imports.
- `package.json` — re-add `@radix-ui/react-tooltip: ^1.2.10` to `dependencies` (alphabetical, between `@radix-ui/react-tabs` and `@vercel/blob`).
- `package-lock.json` — regenerated by the install; must add only the tooltip subtree.
- `components/features/markdown-field.tsx` — **unchanged** (no consumer edits needed; the import path and all four names already match).

## Implementation

- [ ] `npm install @radix-ui/react-tooltip@^1.2.10` — pin the same range #504 removed so no unrelated dep drift lands.
- [ ] Verify `git diff package-lock.json` adds only `@radix-ui/react-tooltip` (plus any Radix transitive it genuinely needs) and does not bump unrelated packages; if it does, revert the lockfile and redo the install off a clean `npm ci`.
- [ ] Create `components/ui/tooltip.tsx`: `'use client'`, named exports only, four function wrappers following `components/ui/dropdown-menu.tsx` line for line — `data-slot="tooltip"` / `"tooltip-trigger"` / `"tooltip-content"` / `"tooltip-provider"`, `React.ComponentProps<typeof TooltipPrimitive.X>` prop types, `cn()` merge, `sideOffset = 4` default.
- [ ] `TooltipContent` renders inside `TooltipPrimitive.Portal` and keeps the previous file's surface tokens and geometry verbatim — `bg-popover text-popover-foreground z-50 max-w-xs overflow-hidden rounded-md border px-3 py-1.5 text-sm shadow-md` — so the tooltip looks as it did on #382's branch. No arrow (the old file had none). Design tokens only, no hardcoded colors.
- [ ] Replace the four dead `animate-slide*AndFade` classes with the live `tw-animate-css` set `dropdown-menu.tsx` already uses: `data-[state=open]:animate-in data-[state=closed]:animate-out`, `fade-in-0`/`fade-out-0`, `zoom-in-95`/`zoom-out-95`, the four `data-[side=*]:slide-in-from-*-2`, plus `origin-(--radix-tooltip-content-transform-origin)`. No `animate-slide*AndFade` anywhere in the new file — those utilities resolve to nothing in this Tailwind 4 setup.
- [ ] `npm run prettier:check`, `npm run eslint:check`, `npm run tsc:check`, `npm run test` — `tsc:check` going green **is** the acceptance criterion for this ticket.
- [ ] Single commit, e.g. `#510 restore ui tooltip primitive and its radix dependency`.

## UX states

Recreating an existing affordance — no new surface, no async state, so no loading/empty/error state to design. Behavior the restore must preserve in the position markdown toolbar (`/positions` create dialog, `/positions/[id]/edit`):

- **Hover / focus on a toolbar button** → tooltip after the caller's `delayDuration={300}`, copy exactly as `markdown-field.tsx` composes it: `Bold (Ctrl+B)`, `Italic (Ctrl+I)`, `Underline (Ctrl+U)`, `Link (Ctrl+K)`, and bare `Heading`, `Bulleted list`, `Numbered list` for the three without shortcuts. Do not restate or duplicate this copy in `tooltip.tsx`.
- **Keyboard** → Radix opens the tooltip on focus and closes on Escape/blur; `TooltipTrigger asChild` keeps the trigger a real `<button>`. Each button also carries its own `aria-label`, so the tooltip is a sighted-discovery aid, not the only label — a11y does not regress even if a tooltip fails to open.
- **Positioning** → portalled, `sideOffset={4}`, so a tooltip on the top row of the toolbar inside the create **dialog** is not clipped by the dialog's overflow. Check this explicitly; it is the one thing a recreated content wrapper can get wrong.
- **Preview mode / submitting** → the toolbar is unmounted in preview mode, and buttons are `disabled` while submitting (a disabled trigger fires no pointer events, so no tooltip). Both are pre-existing #382 behavior; leave as is.
- **Dark mode** → token-based `bg-popover`/`text-popover-foreground` must stay legible in both themes.

## Testing

- [ ] From a clean tree on this branch: `npm ci`, then `npm run tsc:check` — passes with zero errors (fails on `dev` today).
- [ ] `npm run prettier:check`, `npm run eslint:check`, `npm run test` — all green, no new warnings.
- [ ] `npm run dev`, sign in as a manager/admin, open `/positions` → **Create position**: hover each of the 7 formatting buttons; each shows its tooltip with the copy above, and the shortcut variants read `Bold (Ctrl+B)`, `Italic (Ctrl+I)`, `Underline (Ctrl+U)`, `Link (Ctrl+K)`.
- [ ] In that dialog, confirm a tooltip on the **top row** of the toolbar renders fully and is not clipped by the dialog edge.
- [ ] Tab to a toolbar button with the keyboard — tooltip appears on focus, Escape dismisses it, and the button still activates with Enter/Space and applies its formatting to the textarea.
- [ ] Same checks on `/positions/[id]/edit` (the non-dialog form).
- [ ] Toggle **Preview** on: the toolbar disappears with no stray tooltip left on screen. Toggle back to write: tooltips work again.
- [ ] Switch to dark mode and re-hover one tooltip — text is legible against the tooltip background.
- [ ] Confirm the tooltip fades/zooms in rather than appearing with no transition (proves the animation classes are live ones, not the dead `slide*AndFade` set).
- [ ] `git diff dev --stat` touches only `components/ui/tooltip.tsx`, `package.json`, `package-lock.json`.

## Risks / notes

- **Low risk.** Additive: one new leaf primitive plus a dependency that sat in `package.json` until #504 removed it. No schema, no server action, no data fetching, no auth surface, no consumer edits — nothing to validate or scope, so §2/§3 are not in play.
- **Bundle:** `@radix-ui/react-tooltip` is a small client-only primitive on a route that is already a client form. Its removal was a mistake, not a deliberate bundle decision, so re-adding it needs no further justification.
- **Not in scope:** the app-wide `TooltipProvider` question. `markdown-field.tsx` wraps its own toolbar with `delayDuration={300}`, which is correct for a single leaf consumer; do **not** hoist a provider into `components/providers/index.tsx` on this ticket.
- **Not in scope:** #504's other deletions. They are all genuinely unreferenced on `dev` (verified above) — do not restore `calendar`/`command`/`popover`/`query-provider`/the removed queries, and do not re-audit them here.
- **Recurrence:** this class of break (two PRs green in isolation, red once combined) is invisible to per-PR CI, and there is no `knip`/`depcheck` in `package.json` to catch a dead-code deletion racing a new usage. Worth a separate ticket (an unused-export check in CI, and/or requiring dead-code-removal PRs to rebase onto `dev` immediately before merge); out of scope for this fix.
